version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.17
    working_directory: /go/app
    steps:
    - checkout
    - run:
        name: "Run go test"
        command: go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg github.com/zegl/kube-score/... -v github.com/zegl/kube-score/...
    - run:
        name: "Enforce Go Formatted Code"
        command: "! go fmt github.com/zegl/kube-score/... 2>&1 | read"
    - run:
        name: "Validate lint"
        command: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.20.0
          golangci-lint run

workflows:
  version: 2
  build-and-release:
    jobs:
    - test
